twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']

when@test:
    twig:
        debug: '%kernel.debug%'
        strict_variables: '%kernel.debug%'
        auto_reload: true